name       : nlohmann-json
version    : 3.10.2
release    : 4
source     :
    - https://github.com/nlohmann/json/archive/refs/tags/v3.10.2.tar.gz : 081ed0f9f89805c2d96335c3acfa993b39a0a5b4b4cef7edb68dd2210a13458c
license    :
    - CC0-1.0
    - MIT
component  : programming.library
homepage   : https://nlohmann.github.io/json/
summary    : JSON for Modern C++
description: |
    JSON for Modern C++
patterns   :
    - /*
setup      : |
    %cmake_ninja -DJSON_BuildTests=OFF -DJSON_MultipleHeaders=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
