name       : nlohmann-json
version    : 3.9.1
release    : 2
source     :
    - https://github.com/nlohmann/json/archive/v3.9.1.tar.gz : 4cf0df69731494668bdd6460ed8cb269b68de9c19ad8c27abc24cd72605b2d5b
license    :
    - CC0-1.0
    - MIT
component  : programming.library
homepage   : https://nlohmann.github.io/json/
summary    : JSON for Modern C++
description: |
    JSON for Modern C++
patterns   :
    - /*
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF -DJSON_MultipleHeaders=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
