name       : nlohmann-json
version    : 3.10.4
release    : 6
source     :
    - https://github.com/nlohmann/json/archive/refs/tags/v3.10.4.tar.gz : 1155fd1a83049767360e9a120c43c578145db3204d2b309eba49fbbedd0f4ed3
license    :
    - CC0-1.0
    - MIT
component  : programming.library
homepage   : https://nlohmann.github.io/json/
summary    : JSON for Modern C++
description: |
    JSON for Modern C++
patterns   :
    - /*
setup      : |
    %cmake_ninja -DJSON_BuildTests=OFF -DJSON_MultipleHeaders=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
