name       : nlohmann-json
version    : 3.11.2
release    : 8
source     :
    - https://github.com/nlohmann/json/releases/download/v3.11.2/json.tar.xz : 8c4b26bf4b422252e13f332bc5e388ec0ab5c3443d24399acb675e68278d341f
license    :
    - CC0-1.0
    - MIT
component  : programming.library
homepage   : https://nlohmann.github.io/json/
summary    : JSON for Modern C++
description: |
    JSON for Modern C++
patterns   :
    - /*
setup      : |
    %cmake_ninja -DJSON_BuildTests=OFF -DJSON_MultipleHeaders=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
