name       : nlohmann-json
version    : 3.10.0
release    : 3
source     :
    - https://github.com/nlohmann/json/archive/refs/tags/v3.10.0.tar.gz : eb8b07806efa5f95b349766ccc7a8ec2348f3b2ee9975ad879259a371aea8084
license    :
    - CC0-1.0
    - MIT
component  : programming.library
homepage   : https://nlohmann.github.io/json/
summary    : JSON for Modern C++
description: |
    JSON for Modern C++
patterns   :
    - /*
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF -DJSON_MultipleHeaders=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
